services: 
  database: 
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wave_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend-server:
    build: .
    command: node --import tsx src/index.ts
    env_file:
      - src/.env.development
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/wave_db
    expose:
      - "3000"
    depends_on:
      database:
        condition: service_healthy  
    profiles: [backend]

  auth-service:
    build: .
    command: node --import tsx src/index.ts
    env_file:
      - src/.env.development
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/wave_db
    ports:
      - "3003:3000"
    depends_on:
      database:
        condition: service_healthy  
    profiles: [devops]
  
  user-service:
    build: .
    command: node --import tsx src/index.ts
    env_file:
      - src/.env.development
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/wave_db
    ports:
      - "3002:3000"
    depends_on:
      database:
        condition: service_healthy  
    profiles: [devops]

  wallet-service:
    build: .
    command: node --import tsx src/index.ts
    env_file:
      - src/.env.development
    environment:
      DATABASE_URL: postgresql://postgres:postgres@database:5432/wave_db
    ports:
      - "3001:3000"
    depends_on:
      database:
        condition: service_healthy  
    profiles: [devops]

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - auth-service
      - wallet-service
      - user-service
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    profiles: [devops]
    
volumes:
  postgres_data: