apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tigerbeetle-data
  namespace: server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
