name: "Build and Test"
on:
  pull_request:

jobs:
  test:
    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        include:
          - ref: ${{ github.head_ref }}
            repo: ${{ github.event.pull_request.head.repo.full_name }}
            kind: incoming
          - ref: ${{ github.event.pull_request.base.ref }}
            repo: ${{ github.event.pull_request.base.repo.full_name }}
            kind: base

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ matrix.ref }}
          ## Set repository to correctly checkout from forks
          repository: ${{ matrix.repo }}

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: Enable Corepack
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install server dependencies
        working-directory: server
        run: pnpm install --frozen-lockfile

      - name: Run tests with coverage
        working-directory: server
        run: pnpm test --coverage        
      - name: "Upload Coverage"
        uses: actions/upload-artifact@v5
        with:
          name: "coverage-${{ matrix.kind }}"
          path: coverage

  build-and-report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - name: "Install Node"
        uses: actions/setup-node@v6
        with:
          node-version: "24.x"

      - name: "Install Deps"
        run: pnpm install --frozen-lockfile
      - name: "Build"
        run: pnpm run build
      # Remove node_modules to see if this action runs entirely compiled
      - name: "Remove Node Modules"
        run: rm -rf node_modules

      - name: "Download Coverage Artifacts for ${{ github.head_ref}}"
        uses: actions/download-artifact@v6
        with:
          name: coverage-incoming
          path: coverage 

      - name: "Download Coverage Artifacts for main"
        uses: actions/download-artifact@v6
        with:
          name: coverage-base
          path: coverage-base

      - name: "Test Action by generating coverage"
        uses: ./
        with:
          file-coverage-mode: "all"
          json-summary-compare-path: coverage-base/coverage-summary.json
          comment-on: 'pr,commit'
          threshold-icons: '{"0": "🔴", "74": "🟠", "75": "🟢"}'

      - name: "Upload build"
        if: env.ACTIONS_STEP_DEBUG == 'true'
        uses: actions/upload-artifact@v5
        with:
          name: dist
          path: dist